### PR TITLE
Publish robots.txt

### PR DESCRIPTION
**Pull request by szepeviktor**
🤖

### CODE REVIEW

**Comment by szepeviktor** [comment]
🍏 
https://deploy-preview-7--bite-sized-a11y.netlify.app/robots.txt

**Comment by adamlaki** [comment]
Viktor, why do we need a direct robots.txt file?

**Comment by szepeviktor** [comment]
Too many answers, Ádám!

- the lack of robots.txt hurts my feeling
- it is a 404 now https://bite-sized-a11y.com/robots.txt
- [search engines ](https://developers.google.com/search/docs/crawling-indexing/robots/intro)need to be configured: what is allowed, what is not
- it is downloaded without a link
- there are a lot a of files like it https://github.com/szepeviktor/RootFiles
- it is a SEO factor
- ...

**Comment by adamlaki** [comment]
Thanks Viktor!

**Pull request merged**
