### PR TITLE
Add CI workflows

### PR DESCRIPTION
**Pull request by szepeviktor**
- check EditorConfig adherence
- check spelling
- check front-end
- check Markdown files

### CODE REVIEW

**Comment by szepeviktor** [comment]
Now NetFly 🪰 is not so old!

> 1:20:41 PM: Now using node v18.14.0 (npm v9.3.1)

**Comment by szepeviktor** [comment]
@adamlaki 🧑‍🏭

- look at spelling findings
- configure markdownlint
- consider using ESLint on JavaScript files
- the right place for local ignored files is a file specified by git global configuration option `core.excludesFile`: `git config --global core.excludesfile ~/.gitignore` 👀

**Comment by szepeviktor** [comment]
You can see CI running in fork, there is a PR there too.

**Comment by szepeviktor** [comment]
The pagination anchor element may need a `/* stylelint-disable-next-line selector-no-qualifying-type */`

**Comment by adamlaki** [comment]
@szepeviktor thank you Viktor!

**Comment by szepeviktor** [comment]
You're welcome, Ádám.

**Pull request merged**
